services:
  db:
    image: postgres:16
    restart: on-failure
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    restart: on-failure
    environment:
      FLASK_APP: "run.py"
      FLASK_DB_TYPE: "postgres"
      FLASK_DB_USER: "postgres"
      FLASK_DB_NAME: "postgres"
      FLASK_DB_PASSWORD: "secretpass"
      FLASK_DB_HOST: "db"
      FLASK_DB_PORT: "5432"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    restart: on-failure
    ports:
      - "80:80"
    depends_on:
      - backend


volumes:
  postgres_data:
